# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{treevisitor}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tokiro"]
  s.date = %q{2010-04-15}
  s.default_executable = %q{tree.rb}
  s.description = %q{      Implementation of visitor design pattern. It contains a 'tree.rb'
      command line clone of the tree unix tool.
}
  s.email = %q{tokiro.oyama@gmail.com}
  s.executables = ["tree.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "examples/find_files.rb",
     "examples/print_files.rb",
     "lib/tree_visitor.rb",
     "lib/treevisitor.rb",
     "lib/treevisitor/abs_node.rb",
     "lib/treevisitor/cli/cli_tree.rb",
     "lib/treevisitor/dir_processor.rb",
     "lib/treevisitor/dir_tree_walker.rb",
     "lib/treevisitor/leaf_node.rb",
     "lib/treevisitor/tree_node.rb",
     "lib/treevisitor/tree_node_visitor.rb",
     "lib/treevisitor/visitors/block_tree_node_visitor.rb",
     "lib/treevisitor/visitors/build_dir_tree_visitor.rb",
     "lib/treevisitor/visitors/callback_tree_node_visitor.rb",
     "lib/treevisitor/visitors/callback_tree_node_visitor2.rb",
     "lib/treevisitor/visitors/clone_tree_node_visitor.rb",
     "lib/treevisitor/visitors/depth_tree_node_visitor.rb",
     "lib/treevisitor/visitors/flat_print_tree_node_visitors.rb",
     "lib/treevisitor/visitors/print_dir_tree_visitor.rb",
     "lib/treevisitor/visitors/print_tree_node_visitor.rb"
  ]
  s.homepage = %q{http://github.com/tokiro/treevisitor}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Implementation of visitor design pattern}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/treevisitor/dir_processor_spec.rb",
     "spec/treevisitor/dir_tree_walker_spec.rb",
     "spec/treevisitor/tree_node_spec.rb",
     "spec/treevisitor/tree_node_visitor_spec.rb",
     "spec/treevisitor/cli/cli_tree_spec.rb",
     "spec/treevisitor/tree_node_dsl_spec.rb",
     "spec/fixtures/test_dir",
     "spec/fixtures/test_dir/dir.1",
     "spec/fixtures/test_dir/dir.1/dir.1.2",
     "spec/fixtures/test_dir/dir.1/dir.1.2/file.1.2.1",
     "spec/fixtures/test_dir/dir.1/file.1.1",
     "spec/fixtures/test_dir/dir.2",
     "spec/fixtures/test_dir/dir.2/file.2.1",
     "spec/fixtures/test_dir/.dir_with_dot/dummy.txt"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

